# Generated by Django 4.2.16 on 2024-12-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_alt',
            field=models.CharField(blank=True, default='Recipe image', max_length=100, null=True),
        ),
    ]
