# Generated by Django 4.2.16 on 2024-12-07 08:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/file.jpg', force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='recipes/'),
        ),
    ]
