# Generated by Django 4.2.16 on 2024-12-09 15:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/wplicaqbia63wjnvzk5l', force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='recipes/'),
        ),
    ]
