# Generated by Django 4.2.16 on 2024-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
